### ISSUE TITLE
Timezone based date parsing causing error

### ISSUE THREAD

**Issue by ephraimd** [burhanahmeed/time.ts#5]
Hi, thanks for this wonderful repo.
I tried the following while using the library in my project

```javascript
time(new String('1606163400000').toString()).tz('America/New_York').t;
```

I get the following error
```shell
error: Uncaught RangeError: Invalid time value
            this.manipulated =  new Date(getUTCMilisecond + Number(addedtime.text)).toISOString();   
                                                                                    ^
    at Date.toISOString (<anonymous>)
    at Timezone.exec (timezone.ts:35:85)
    at Time.tz (time.ts:46:33)
```

Your help fixing this would be really appreciated.

**Comment by burhanahmeed** [comment]
you can simply combine it with native javascipt date.

```javascript
const date = new Date(1606163400000).toISOString() // 2020-11-23T20:30:00.000Z
time(date).tz('America/New_York').t; // 2020-11-23T15:30:00.000Z
```

**Comment by ephraimd** [comment]
Thank you @burhanahmeed , that solved it!
